[package]
name = "rawspeed-codecs-packed-encoder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-bitstream-bitstream-encoder= { path = "../../../bitstream/bitstream/encoder" }
rawspeed-bitstream-bitstreamcache = { path = "../../../bitstream/bitstreamcache" }
rawspeed-bitstream-bitstreams = { path = "../../../bitstream/bitstreams" }
rawspeed-common-generic_num = { path = "../../../common/generic_num" }
rawspeed-memory-endianness = { path = "../../../memory/endianness" }
rawspeed-std = { path = "../../../std" }
rawspeed-std-ndslice = { path = "../../../std/ndslice" }

[lib]
path = "mod.rs"
