[package]
name = "rawspeed-codecs-packed-encoder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-common = { path = "../../../common" }
rawspeed-memory-bitstreamcache = { path = "../../../memory/bitstreamcache" }
rawspeed-memory-bitstreams = { path = "../../../memory/bitstreams" }
rawspeed-memory-bitvacuumer = { path = "../../../memory/bitvacuumer" }
rawspeed-memory-endianness = { path = "../../../memory/endianness" }
rawspeed-std = { path = "../../../std" }
rawspeed-std-ndslice = { path = "../../../std/ndslice" }

[lib]
path = "mod.rs"
