[package]
name = "rawspeed-utils-librstest"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-common-generic_num = { path = "../../common/generic_num" }
rawspeed-metadata-camerametadata = { path = "../../metadata/camerametadata" }
rawspeed-metadata-camerasxml_parser = { path = "../../metadata/camerasxml_parser" }
rawspeed-misc-md5 = { path = "../../misc/md5" }
rawspeed-parsers-rawparser = { path = "../../parsers/rawparser" }
rawspeed-demuxers-rawdemuxer = { path = "../../demuxers/rawdemuxer" }
rawspeed-std = { path = "../../std" }
rawspeed-std-ndslice = { path = "../../std/ndslice" }
rawspeed-memory-nd_slice_procurement = { path = "../../memory/nd-slice-procurement" }
rawspeed-metadata-colorfilterarray = { path = "../../metadata/colorfilterarray" }

[dev-dependencies]
rawspeed-metadata-xmlparser = { path = "../../metadata/xmlparser" }

[lib]
path = "mod.rs"
bench = false
