[package]
name = "rawspeed-utils-librstest"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-common-generic_num = { workspace = true }
rawspeed-metadata-camerametadata = { workspace = true }
rawspeed-metadata-camerasxml_parser = { workspace = true }
rawspeed-misc-md5 = { workspace = true }
rawspeed-parsers-rawparser = { workspace = true }
rawspeed-demuxers-rawdemuxer = { workspace = true }
rawspeed-std = { workspace = true }
rawspeed-std-ndslice = { workspace = true }
rawspeed-memory-nd_slice_procurement = { workspace = true }
rawspeed-metadata-colorfilterarray = { workspace = true }

[dev-dependencies]
rawspeed-metadata-xmlparser = { workspace = true }

[lib]
path = "mod.rs"
bench = false
