[package]
name = "rawspeed-bitstream-bitstream-encoder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-bitstream-bitstreamcache = { workspace = true }
rawspeed-bitstream-bitstreams = { workspace = true }
rawspeed-common-bitseq = { workspace = true }
rawspeed-common-generic_num = { workspace = true }
rawspeed-memory-endianness = { workspace = true }

[lib]
path = "mod.rs"
bench = false
