[package]
name = "rawspeed-bitstream-bitstream-encoder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rawspeed-bitstream-bitstreamcache = { path = "../../bitstreamcache" }
rawspeed-bitstream-bitstreams = { path = "../../bitstreams" }
rawspeed-common-bitseq = { path = "../../../common/bitseq" }
rawspeed-common-generic_num = { path = "../../../common/generic_num" }
rawspeed-memory-endianness = { path = "../../../memory/endianness" }

[lib]
path = "mod.rs"
bench = false
